---
title: "So Long, Marley!"
author: "Kim Sweeney"
date: "June 10, 2025"
year: 2025
image: "../../../assets/news/2025/so-long-marley.jpg"
pony: false
summary: |-
  On November 11, 2023 a registered purebred, five year-old chestnut Arabian was donated to the rescue to raise funds. Marley had sustained a soft tissue injury during a storm and had been cast in his stall. Upon taking this sweet boy, we knew he had months of rehab. Time passed, many vet visits and stall rest gave way to Marley being ready to go to a new home. I was sad to see this guy go as I transported him to Georgia, but knew he would do great things. Unfortunately, Marley was unable to perform the job his adoptee needed him to do, and he was returned months later. Marley is a very high energy working horse and does not do well idle he needs a lot of structure and routine.

  Almost all the rescues are out 24/7 with access to shelters. We have a total of 13 stalls, but only use those when necessary. Marley had been stalled his whole life being let out once a day. How was he ever going to adjust to being turned out 24/7? How unfair it would be for him to be alone in the barn. We tried several approaches trying to figure out what was the best for him, and then I got a message from one of our long-time followers, Sonja Roberts, that she may have a solution. Sonja is a wonderful lady who has an Arab and happened to be friends with a wonderful lady in Ocala who had a yearling Arab and was a retired trainer. The rescue agreed to pay for all of Marley’s hay, grain, dental, vetting, Ferrier, massage chiropractic, or anything he needed. The wonderful Heather Kolman gave him her expertise care and most of all her love.

  Over the past year I have seen this horse totally transform. It has been a pleasure to go visit quite often and see how he has changed. I received a call from Heather in May advising me she was moving to Danville, Kentucky and asked me if she could take Marley. I never once hesitated and tearfully told her she was such a gift to both Marley and myself. She told me she knew he was with her for a reason. Marley spending the rest of his life with Heather is the best outcome he could ever have. I went yesterday to say goodbye to him, of course he tried to bite me several times because that’s just who he is. But I could tell when I looked at his face that he was thanking me. I realized yesterday was not goodbye, as I travel to Ohio several times a year. I will just have to stop off in Kentucky to see how my favorite chestnut Arab is doing.

  I will forever be grateful for both Sonja and Heather. Marley was donated to the Rescue to make money, wound up being that he cost the Rescue a lot of money. There was no adoption fee. I gladly gave him to Heather, because there is no way to put a price on what that sweet boy was worth and all that she has done for him. So today as they take their 10 1/2 hour trip to their forever home. I am sad, but I am overjoyed because this is the perfect life for our sweet boy.

  Congrats, Heather! Many blessings to you as you start your new adventure with your horse, who is now lovingly referred to as Red.
---

On November 11, 2023 a registered purebred, five year-old chestnut Arabian was donated to the rescue to raise funds. Marley had sustained a soft tissue injury during a storm and had been cast in his stall. Upon taking this sweet boy, we knew he had months of rehab. Time passed, many vet visits and stall rest gave way to Marley being ready to go to a new home. I was sad to see this guy go as I transported him to Georgia, but knew he would do great things. Unfortunately, Marley was unable to perform the job his adoptee needed him to do, and he was returned months later. Marley is a very high energy working horse and does not do well idle he needs a lot of structure and routine.

Almost all the rescues are out 24/7 with access to shelters. We have a total of 13 stalls, but only use those when necessary. Marley had been stalled his whole life being let out once a day. How was he ever going to adjust to being turned out 24/7? How unfair it would be for him to be alone in the barn. We tried several approaches trying to figure out what was the best for him, and then I got a message from one of our long-time followers, Sonja Roberts, that she may have a solution. Sonja is a wonderful lady who has an Arab and happened to be friends with a wonderful lady in Ocala who had a yearling Arab and was a retired trainer. The rescue agreed to pay for all of Marley’s hay, grain, dental, vetting, Ferrier, massage chiropractic, or anything he needed. The wonderful Heather Kolman gave him her expertise care and most of all her love.

Over the past year I have seen this horse totally transform. It has been a pleasure to go visit quite often and see how he has changed. I received a call from Heather in May advising me she was moving to Danville, Kentucky and asked me if she could take Marley. I never once hesitated and tearfully told her she was such a gift to both Marley and myself. She told me she knew he was with her for a reason. Marley spending the rest of his life with Heather is the best outcome he could ever have. I went yesterday to say goodbye to him, of course he tried to bite me several times because that’s just who he is. But I could tell when I looked at his face that he was thanking me. I realized yesterday was not goodbye, as I travel to Ohio several times a year. I will just have to stop off in Kentucky to see how my favorite chestnut Arab is doing.

I will forever be grateful for both Sonja and Heather. Marley was donated to the Rescue to make money, wound up being that he cost the Rescue a lot of money. There was no adoption fee. I gladly gave him to Heather, because there is no way to put a price on what that sweet boy was worth and all that she has done for him. So today as they take their 10 1/2 hour trip to their forever home. I am sad, but I am overjoyed because this is the perfect life for our sweet boy.

Congrats, Heather! Many blessings to you as you start your new adventure with your horse, who is now lovingly referred to as Red.
